-- Chu Xiaomai secure Supabase schema / migration.
-- Run this whole file in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------

create table if not exists public.admin_users (
  email text primary key,
  user_id uuid unique references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.admin_users
  add column if not exists user_id uuid references auth.users(id) on delete set null;

do $$
begin
  update public.admin_users admin_user
  set email = auth_user.email
  from auth.users auth_user
  where admin_user.user_id = auth_user.id
    and admin_user.email is null;

  delete from public.admin_users
  where email is null;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'admin_users'
      and column_name = 'email'
      and is_nullable = 'YES'
  ) then
    alter table public.admin_users alter column email set not null;
  end if;
end;
$$;

create unique index if not exists admin_users_email_unique
on public.admin_users (email);

create unique index if not exists admin_users_user_id_unique
on public.admin_users (user_id)
where user_id is not null;

create table if not exists public.security_settings (
  id boolean primary key default true check (id),
  vote_cookie_per_minute integer not null default 30 check (vote_cookie_per_minute > 0),
  vote_ip_per_minute integer not null default 120 check (vote_ip_per_minute > 0),
  max_likes_per_period integer not null default 20 check (max_likes_per_period > 0),
  submission_cookie_per_minute integer not null default 3 check (submission_cookie_per_minute > 0),
  submission_ip_per_minute integer not null default 30 check (submission_ip_per_minute > 0),
  submission_cookie_per_period integer not null default 10 check (submission_cookie_per_period > 0),
  updated_at timestamptz not null default now()
);

insert into public.security_settings (id)
values (true)
on conflict (id) do nothing;

create table if not exists public.songs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  artist text not null,
  title_lower text not null,
  artist_lower text not null,
  playlist_date text not null,
  likes_count integer not null default 0,
  created_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.song_likes (
  id uuid primary key default gen_random_uuid(),
  song_id uuid not null references public.songs(id) on delete cascade,
  user_id text not null,
  voter_cookie text,
  voter_ip text,
  playlist_date text not null,
  created_at timestamptz not null default now(),
  unique (song_id, user_id, playlist_date)
);

create table if not exists public.playlist_periods (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  check (ends_at > starts_at)
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null,
  is_active boolean not null default true,
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vote_attempts (
  id bigint generated by default as identity primary key,
  attempt_type text not null check (attempt_type in ('vote', 'submission')),
  playlist_date text not null,
  voter_cookie text,
  voter_ip text,
  created_at timestamptz not null default now()
);

alter table public.song_likes
  add column if not exists voter_cookie text,
  add column if not exists voter_ip text;

update public.song_likes
set voter_cookie = coalesce(voter_cookie, user_id)
where voter_cookie is null;

-- Keep existing data from breaking the migration; NOT VALID constraints still
-- protect all new/updated rows.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'songs_title_length_check'
      and conrelid = 'public.songs'::regclass
  ) then
    alter table public.songs
      add constraint songs_title_length_check
      check (char_length(btrim(title)) between 1 and 80) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'songs_artist_length_check'
      and conrelid = 'public.songs'::regclass
  ) then
    alter table public.songs
      add constraint songs_artist_length_check
      check (char_length(btrim(artist)) between 1 and 80) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'songs_likes_count_nonnegative'
      and conrelid = 'public.songs'::regclass
  ) then
    alter table public.songs
      add constraint songs_likes_count_nonnegative
      check (likes_count >= 0) not valid;
  end if;
end;
$$;

create index if not exists songs_playlist_date_idx on public.songs (playlist_date);
create index if not exists songs_title_lower_idx on public.songs (title_lower);
create index if not exists songs_artist_lower_idx on public.songs (artist_lower);

-- Merge existing duplicate submissions before enforcing the per-period
-- title/artist uniqueness rule. The oldest row is kept and duplicate likes are
-- moved when possible.
drop table if exists pg_temp.tmp_duplicate_songs;
create temp table tmp_duplicate_songs on commit drop as
with ranked_songs as (
  select
    id,
    first_value(id) over (
      partition by playlist_date, title_lower, artist_lower
      order by created_at asc, id asc
    ) as keeper_id,
    row_number() over (
      partition by playlist_date, title_lower, artist_lower
      order by created_at asc, id asc
    ) as duplicate_rank
  from public.songs
)
select id as duplicate_id, keeper_id
from ranked_songs
where duplicate_rank > 1;

with affected_likes as (
  select
    like_row.id,
    coalesce(duplicate_song.keeper_id, like_row.song_id) as target_song_id,
    like_row.playlist_date,
    like_row.user_id,
    like_row.created_at
  from public.song_likes like_row
  left join pg_temp.tmp_duplicate_songs duplicate_song
    on duplicate_song.duplicate_id = like_row.song_id
  where duplicate_song.keeper_id is not null
    or like_row.song_id in (select keeper_id from pg_temp.tmp_duplicate_songs)
),
ranked_likes as (
  select
    id,
    row_number() over (
      partition by target_song_id, playlist_date, user_id
      order by created_at asc, id asc
    ) as duplicate_rank
  from affected_likes
)
delete from public.song_likes like_row
using ranked_likes
where like_row.id = ranked_likes.id
  and ranked_likes.duplicate_rank > 1;

with affected_likes as (
  select
    like_row.id,
    coalesce(duplicate_song.keeper_id, like_row.song_id) as target_song_id,
    like_row.playlist_date,
    like_row.voter_cookie,
    like_row.created_at
  from public.song_likes like_row
  left join pg_temp.tmp_duplicate_songs duplicate_song
    on duplicate_song.duplicate_id = like_row.song_id
  where like_row.voter_cookie is not null
    and (
      duplicate_song.keeper_id is not null
      or like_row.song_id in (select keeper_id from pg_temp.tmp_duplicate_songs)
    )
),
ranked_likes as (
  select
    id,
    row_number() over (
      partition by target_song_id, playlist_date, voter_cookie
      order by created_at asc, id asc
    ) as duplicate_rank
  from affected_likes
)
delete from public.song_likes like_row
using ranked_likes
where like_row.id = ranked_likes.id
  and ranked_likes.duplicate_rank > 1;

update public.song_likes like_row
set song_id = duplicate_song.keeper_id
from pg_temp.tmp_duplicate_songs duplicate_song
where like_row.song_id = duplicate_song.duplicate_id;

delete from public.songs song
using pg_temp.tmp_duplicate_songs duplicate_song
where song.id = duplicate_song.duplicate_id;

update public.songs song
set likes_count = (
  select count(*)::integer
  from public.song_likes like_row
  where like_row.song_id = song.id
);

create unique index if not exists songs_period_title_artist_unique
on public.songs (playlist_date, title_lower, artist_lower);

create index if not exists song_likes_user_playlist_idx on public.song_likes (user_id, playlist_date);
create index if not exists song_likes_cookie_playlist_idx on public.song_likes (voter_cookie, playlist_date);
create unique index if not exists song_likes_song_cookie_unique
on public.song_likes (song_id, playlist_date, voter_cookie)
where voter_cookie is not null;
drop index if exists public.song_likes_song_ip_unique;

create index if not exists playlist_periods_status_idx on public.playlist_periods (status);
create index if not exists playlist_periods_created_at_idx on public.playlist_periods (created_at desc);
create index if not exists playlist_periods_starts_at_idx on public.playlist_periods (starts_at);

create index if not exists announcements_is_active_idx on public.announcements (is_active);
create index if not exists announcements_created_at_idx on public.announcements (created_at desc);

create index if not exists vote_attempts_cookie_created_idx
on public.vote_attempts (attempt_type, voter_cookie, created_at desc);
create index if not exists vote_attempts_ip_created_idx
on public.vote_attempts (attempt_type, voter_ip, created_at desc);
create index if not exists vote_attempts_created_at_idx
on public.vote_attempts (created_at);

-- ---------------------------------------------------------------------
-- Helper functions
-- ---------------------------------------------------------------------

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and exists (
      select 1
      from public.admin_users admin_user
      where lower(admin_user.email) = lower(auth.email())
    );
$$;

create or replace function public.is_admin_email_allowed(p_email text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users admin_user
    where lower(admin_user.email) = lower(nullif(btrim(p_email), ''))
  );
$$;

create or replace function public.request_client_ip()
returns text
language plpgsql
stable
set search_path = public
as $$
declare
  headers jsonb := '{}'::jsonb;
  header_text text;
  raw_ip text;
begin
  header_text := current_setting('request.headers', true);

  if header_text is not null and header_text <> '' then
    begin
      headers := header_text::jsonb;
    exception when others then
      headers := '{}'::jsonb;
    end;
  end if;

  raw_ip := coalesce(
    headers ->> 'cf-connecting-ip',
    headers ->> 'x-real-ip',
    split_part(headers ->> 'x-forwarded-for', ',', 1)
  );

  raw_ip := nullif(btrim(raw_ip), '');
  if raw_ip is null then
    return null;
  end if;

  return left(raw_ip, 128);
end;
$$;

create or replace function public.assert_valid_voter_cookie(p_voter_cookie text)
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  normalized_cookie text := nullif(btrim(p_voter_cookie), '');
begin
  if normalized_cookie is null
    or length(normalized_cookie) < 8
    or length(normalized_cookie) > 128
    or normalized_cookie !~ '^[A-Za-z0-9_-]+$'
  then
    raise exception 'Browser cookies are required before submitting or voting.';
  end if;

  return normalized_cookie;
end;
$$;

create or replace function public.record_rate_limited_attempt(
  p_attempt_type text,
  p_playlist_date text,
  p_voter_cookie text,
  p_voter_ip text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  settings public.security_settings%rowtype;
  cookie_count integer;
  ip_count integer;
begin
  if p_playlist_date is null or length(p_playlist_date) > 64 then
    raise exception 'Invalid playlist period.';
  end if;

  select *
  into settings
  from public.security_settings
  where public.security_settings.id = true;

  if not found then
    raise exception 'Security settings are missing.';
  end if;

  delete from public.vote_attempts
  where created_at < now() - interval '7 days';

  if p_attempt_type = 'vote' then
    select count(*)::integer into cookie_count
    from public.vote_attempts
    where attempt_type = 'vote'
      and voter_cookie = p_voter_cookie
      and created_at >= now() - interval '1 minute';

    if cookie_count >= settings.vote_cookie_per_minute then
      raise exception 'Voting too frequently. Please wait a minute and try again.';
    end if;

    if p_voter_ip is not null then
      select count(*)::integer into ip_count
      from public.vote_attempts
      where attempt_type = 'vote'
        and voter_ip = p_voter_ip
        and created_at >= now() - interval '1 minute';

      if ip_count >= settings.vote_ip_per_minute then
        raise exception 'This network is voting too frequently. Please wait a minute and try again.';
      end if;
    end if;
  elsif p_attempt_type = 'submission' then
    select count(*)::integer into cookie_count
    from public.vote_attempts
    where attempt_type = 'submission'
      and voter_cookie = p_voter_cookie
      and created_at >= now() - interval '1 minute';

    if cookie_count >= settings.submission_cookie_per_minute then
      raise exception 'Submitting too frequently. Please wait a minute and try again.';
    end if;

    if p_voter_ip is not null then
      select count(*)::integer into ip_count
      from public.vote_attempts
      where attempt_type = 'submission'
        and voter_ip = p_voter_ip
        and created_at >= now() - interval '1 minute';

      if ip_count >= settings.submission_ip_per_minute then
        raise exception 'This network is submitting too frequently. Please wait a minute and try again.';
      end if;
    end if;
  else
    raise exception 'Unknown rate limit type.';
  end if;

  insert into public.vote_attempts (attempt_type, playlist_date, voter_cookie, voter_ip)
  values (p_attempt_type, p_playlist_date, p_voter_cookie, p_voter_ip);
end;
$$;

create or replace function public.get_my_likes(
  p_playlist_date text,
  p_voter_cookie text
)
returns table (song_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_cookie text;
begin
  normalized_cookie := public.assert_valid_voter_cookie(p_voter_cookie);

  return query
  select like_row.song_id
  from public.song_likes like_row
  where like_row.playlist_date = p_playlist_date
    and like_row.voter_cookie = normalized_cookie
  order by like_row.created_at desc
  limit 500;
end;
$$;

create or replace function public.toggle_song_like(
  p_song_id uuid,
  p_playlist_date text,
  p_voter_cookie text,
  p_action text
)
returns table (liked boolean, likes_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_cookie text;
  client_ip text;
  next_likes_count integer := 0;
  max_likes integer;
  already_liked boolean := false;
begin
  normalized_cookie := public.assert_valid_voter_cookie(p_voter_cookie);
  client_ip := public.request_client_ip();
  perform public.record_rate_limited_attempt('vote', p_playlist_date, normalized_cookie, client_ip);

  if p_action not in ('like', 'unlike') then
    raise exception 'Unknown voting action.';
  end if;

  if not exists (
    select 1
    from public.songs song
    join public.playlist_periods period on period.id::text = song.playlist_date
    where song.id = p_song_id
      and song.playlist_date = p_playlist_date
      and period.status = 'active'
      and now() between period.starts_at and period.ends_at
  ) then
    raise exception 'This song is not in an open voting period.';
  end if;

  select exists (
    select 1
    from public.song_likes
    where song_id = p_song_id
      and playlist_date = p_playlist_date
      and voter_cookie = normalized_cookie
  ) into already_liked;

  if p_action = 'like' and not already_liked then
    select max_likes_per_period
    into max_likes
    from public.security_settings
    where public.security_settings.id = true;

    if (
      select count(*)::integer
      from public.song_likes
      where playlist_date = p_playlist_date
        and voter_cookie = normalized_cookie
    ) >= max_likes then
      raise exception 'This browser has reached the like limit for this period.';
    end if;

    insert into public.song_likes (song_id, user_id, playlist_date, voter_cookie, voter_ip)
    values (p_song_id, normalized_cookie, p_playlist_date, normalized_cookie, client_ip);
  elsif p_action = 'unlike' then
    delete from public.song_likes
    where song_id = p_song_id
      and playlist_date = p_playlist_date
      and voter_cookie = normalized_cookie;
  end if;

  update public.songs
  set likes_count = (
    select count(*)::integer
    from public.song_likes
    where song_id = p_song_id
      and playlist_date = p_playlist_date
  )
  where public.songs.id = p_song_id
  returning public.songs.likes_count into next_likes_count;

  return query
  select exists (
    select 1
    from public.song_likes
    where song_id = p_song_id
      and playlist_date = p_playlist_date
      and voter_cookie = normalized_cookie
  ), coalesce(next_likes_count, 0);
end;
$$;

create or replace function public.submit_song(
  p_title text,
  p_artist text,
  p_playlist_date text,
  p_voter_cookie text
)
returns table (
  id uuid,
  title text,
  artist text,
  playlist_date text,
  likes_count integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_cookie text;
  client_ip text;
  clean_title text := btrim(coalesce(p_title, ''));
  clean_artist text := btrim(coalesce(p_artist, ''));
  clean_title_lower text;
  clean_artist_lower text;
  max_submissions integer;
  submitter_hash text;
begin
  normalized_cookie := public.assert_valid_voter_cookie(p_voter_cookie);
  client_ip := public.request_client_ip();
  perform public.record_rate_limited_attempt('submission', p_playlist_date, normalized_cookie, client_ip);

  if char_length(clean_title) < 1 or char_length(clean_title) > 80 then
    raise exception 'Song title must be 1-80 characters.';
  end if;

  if char_length(clean_artist) < 1 or char_length(clean_artist) > 80 then
    raise exception 'Artist name must be 1-80 characters.';
  end if;

  if not exists (
    select 1
    from public.playlist_periods period
    where period.id::text = p_playlist_date
      and period.status = 'active'
      and now() between period.starts_at and period.ends_at
  ) then
    raise exception 'The current period is not open for submissions.';
  end if;

  submitter_hash := 'cookie:' || md5(normalized_cookie);

  select submission_cookie_per_period
  into max_submissions
  from public.security_settings
  where public.security_settings.id = true;

  if (
    select count(*)::integer
    from public.songs song
    where song.playlist_date = p_playlist_date
      and song.created_by = submitter_hash
  ) >= max_submissions then
    raise exception 'This browser has reached the submission limit for this period.';
  end if;

  clean_title_lower := lower(clean_title);
  clean_artist_lower := lower(clean_artist);

  if exists (
    select 1
    from public.songs song
    where song.playlist_date = p_playlist_date
      and song.title_lower = clean_title_lower
      and song.artist_lower = clean_artist_lower
  ) then
    raise exception 'This song is already in the current playlist.';
  end if;

  return query
  insert into public.songs (
    title,
    artist,
    title_lower,
    artist_lower,
    playlist_date,
    likes_count,
    created_by
  )
  values (
    clean_title,
    clean_artist,
    clean_title_lower,
    clean_artist_lower,
    p_playlist_date,
    0,
    submitter_hash
  )
  returning public.songs.id,
    public.songs.title,
    public.songs.artist,
    public.songs.playlist_date,
    public.songs.likes_count,
    public.songs.created_at;
end;
$$;

-- ---------------------------------------------------------------------
-- RLS and privileges
-- ---------------------------------------------------------------------

alter table public.admin_users enable row level security;
alter table public.security_settings enable row level security;
alter table public.songs enable row level security;
alter table public.song_likes enable row level security;
alter table public.playlist_periods enable row level security;
alter table public.announcements enable row level security;
alter table public.vote_attempts enable row level security;

-- Remove old/dangerous policies by every historical name used in this repo.
drop policy if exists "songs_select_all" on public.songs;
drop policy if exists "songs_select_policy" on public.songs;
drop policy if exists "songs_insert_all" on public.songs;
drop policy if exists "songs_insert_policy" on public.songs;
drop policy if exists "songs_update_all" on public.songs;
drop policy if exists "songs_update_policy" on public.songs;
drop policy if exists "songs_update_block_direct_votes" on public.songs;

drop policy if exists "likes_select_all" on public.song_likes;
drop policy if exists "likes_select_policy" on public.song_likes;
drop policy if exists "likes_insert_all" on public.song_likes;
drop policy if exists "likes_insert_policy" on public.song_likes;
drop policy if exists "likes_insert_block_direct_votes" on public.song_likes;
drop policy if exists "likes_delete_all" on public.song_likes;
drop policy if exists "likes_delete_policy" on public.song_likes;
drop policy if exists "likes_delete_block_direct_votes" on public.song_likes;

drop policy if exists "playlist_periods_select_all" on public.playlist_periods;
drop policy if exists "playlist_periods_insert_all" on public.playlist_periods;
drop policy if exists "playlist_periods_update_all" on public.playlist_periods;

drop policy if exists "announcements_select_all" on public.announcements;
drop policy if exists "announcements_select_policy" on public.announcements;
drop policy if exists "announcements_insert_all" on public.announcements;
drop policy if exists "announcements_insert_policy" on public.announcements;
drop policy if exists "announcements_update_all" on public.announcements;
drop policy if exists "announcements_update_policy" on public.announcements;

drop policy if exists "admin_users_select_admin" on public.admin_users;
drop policy if exists "admin_users_manage_admin" on public.admin_users;
drop policy if exists "security_settings_select_admin" on public.security_settings;
drop policy if exists "security_settings_update_admin" on public.security_settings;
drop policy if exists "songs_select_public" on public.songs;
drop policy if exists "songs_select_admin" on public.songs;
drop policy if exists "song_likes_select_admin" on public.song_likes;
drop policy if exists "playlist_periods_select_public" on public.playlist_periods;
drop policy if exists "playlist_periods_insert_admin" on public.playlist_periods;
drop policy if exists "playlist_periods_update_admin" on public.playlist_periods;
drop policy if exists "playlist_periods_delete_admin" on public.playlist_periods;
drop policy if exists "announcements_select_public_or_admin" on public.announcements;
drop policy if exists "announcements_insert_admin" on public.announcements;
drop policy if exists "announcements_update_admin" on public.announcements;
drop policy if exists "announcements_delete_admin" on public.announcements;

revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.security_settings from anon, authenticated;
revoke all on table public.songs from anon, authenticated;
revoke all on table public.song_likes from anon, authenticated;
revoke all on table public.playlist_periods from anon, authenticated;
revoke all on table public.announcements from anon, authenticated;
revoke all on table public.vote_attempts from anon, authenticated;

grant select (id, title, artist, title_lower, artist_lower, playlist_date, likes_count, created_at)
on public.songs to anon, authenticated;

grant select (id, title, starts_at, ends_at, status, created_at, updated_at, archived_at)
on public.playlist_periods to anon, authenticated;
grant insert, update, delete on public.playlist_periods to authenticated;

grant select (id, title, content, is_active, created_at, updated_at)
on public.announcements to anon, authenticated;
grant insert, update, delete on public.announcements to authenticated;

grant select on public.song_likes to authenticated;
grant select, insert, update, delete on public.admin_users to authenticated;
grant select, update on public.security_settings to authenticated;

revoke all on function public.is_current_user_admin() from public;
revoke all on function public.is_admin_email_allowed(text) from public;
revoke all on function public.request_client_ip() from public;
revoke all on function public.assert_valid_voter_cookie(text) from public;
revoke all on function public.record_rate_limited_attempt(text, text, text, text) from public;
revoke all on function public.get_my_likes(text, text) from public;
revoke all on function public.toggle_song_like(uuid, text, text, text) from public;
revoke all on function public.submit_song(text, text, text, text) from public;

grant execute on function public.is_current_user_admin() to anon, authenticated;
grant execute on function public.is_admin_email_allowed(text) to anon, authenticated;
grant execute on function public.get_my_likes(text, text) to anon, authenticated;
grant execute on function public.toggle_song_like(uuid, text, text, text) to anon, authenticated;
grant execute on function public.submit_song(text, text, text, text) to anon, authenticated;
grant usage on schema public to anon, authenticated;

create policy "admin_users_select_admin"
on public.admin_users
for select
to authenticated
using (public.is_current_user_admin());

create policy "admin_users_manage_admin"
on public.admin_users
for all
to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy "security_settings_select_admin"
on public.security_settings
for select
to authenticated
using (public.is_current_user_admin());

create policy "security_settings_update_admin"
on public.security_settings
for update
to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy "songs_select_public"
on public.songs
for select
to anon, authenticated
using (true);

create policy "song_likes_select_admin"
on public.song_likes
for select
to authenticated
using (public.is_current_user_admin());

create policy "playlist_periods_select_public"
on public.playlist_periods
for select
to anon, authenticated
using (true);

create policy "playlist_periods_insert_admin"
on public.playlist_periods
for insert
to authenticated
with check (public.is_current_user_admin() and created_by = auth.uid()::text);

create policy "playlist_periods_update_admin"
on public.playlist_periods
for update
to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy "playlist_periods_delete_admin"
on public.playlist_periods
for delete
to authenticated
using (public.is_current_user_admin());

create policy "announcements_select_public_or_admin"
on public.announcements
for select
to anon, authenticated
using (is_active = true or public.is_current_user_admin());

create policy "announcements_insert_admin"
on public.announcements
for insert
to authenticated
with check (public.is_current_user_admin() and created_by = auth.uid()::text);

create policy "announcements_update_admin"
on public.announcements
for update
to authenticated
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy "announcements_delete_admin"
on public.announcements
for delete
to authenticated
using (public.is_current_user_admin());

-- vote_attempts has no client-facing policies. It is written only by
-- SECURITY DEFINER RPC functions.

notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------
-- Admin bootstrap helper
-- ---------------------------------------------------------------------
-- Admin bootstrap helper.
-- Replace the email/password and run it in SQL Editor to create or update a
-- password-based Supabase Auth user and grant admin access.
--
-- do $$
-- declare
--   admin_email text := 'admin@example.com';
--   admin_password text := 'ChangeMe_123456';
--   admin_user_id uuid;
-- begin
--   if length(admin_password) < 8 then
--     raise exception 'Admin password must be at least 8 characters.';
--   end if;
--
--   select id
--   into admin_user_id
--   from auth.users
--   where lower(email) = lower(admin_email)
--   limit 1;
--
--   if admin_user_id is null then
--     admin_user_id := gen_random_uuid();
--
--     insert into auth.users (
--       instance_id,
--       id,
--       aud,
--       role,
--       email,
--       encrypted_password,
--       email_confirmed_at,
--       created_at,
--       updated_at,
--       raw_app_meta_data,
--       raw_user_meta_data,
--       is_super_admin,
--       confirmation_token,
--       email_change,
--       email_change_token_new,
--       recovery_token
--     )
--     values (
--       '00000000-0000-0000-0000-000000000000',
--       admin_user_id,
--       'authenticated',
--       'authenticated',
--       admin_email,
--       crypt(admin_password, gen_salt('bf')),
--       now(),
--       now(),
--       now(),
--       '{"provider":"email","providers":["email"]}'::jsonb,
--       '{}'::jsonb,
--       false,
--       '',
--       '',
--       '',
--       ''
--     );
--
--     insert into auth.identities (
--       id,
--       user_id,
--       provider_id,
--       identity_data,
--       provider,
--       last_sign_in_at,
--       created_at,
--       updated_at
--     )
--     values (
--       admin_user_id,
--       admin_user_id,
--       admin_user_id::text,
--       jsonb_build_object('sub', admin_user_id::text, 'email', admin_email),
--       'email',
--       now(),
--       now(),
--       now()
--     )
--     on conflict do nothing;
--   else
--     update auth.users
--     set encrypted_password = crypt(admin_password, gen_salt('bf')),
--         email_confirmed_at = coalesce(email_confirmed_at, now()),
--         updated_at = now()
--     where id = admin_user_id;
--   end if;
--
--   insert into public.admin_users (email, user_id)
--   values (admin_email, admin_user_id)
--   on conflict (email) do update
--   set user_id = excluded.user_id;
-- end;
-- $$;
